
```{r finding_and_removing_accuracy_outliers}
#| code-summary: "Removing incorrect trials and task-wise accuracy outliers"
#| echo: true
#| output: false

# ═══ Accuracy outliers analysis ═══════════════════════════════════════════════

# ─── Listing error rates per subject ───
list(df_explicit, df_implicit) |> 
  imap(
    ~.x |> 
      select(subjectid, starts_with("correct"), aphantasia) |> 
      group_by(subjectid) |> 
      count(pick(2)) |> 
      filter(pick(1) == 1) |> 
      ungroup() |> 
      mutate(
        n_tot = max(n),
        prop = (n_tot - n) / n_tot * 100  # analyzing the error rate per subject
      ) %>%
      arrange(desc(prop)) |> 
      select(1, 5)
    )
# 5 accuracy outliers in the explicit task, 4 in the implicit one

# ─── Removing incorrect trials and task-wise accuracy outliers ───
df_explicit_rt <-
  df_explicit |> 
  # filtering out...
  filter(
    # incorrect trials
    correct_explicit == 1 &
    # participants identified with with high error rates
    !(subjectid %in% c( 
      "aknezevic",
      "lbrunie", 
      "agayou", 
      "bluciani",
      "ldossantos"))
    ) |>  
  # removing irrelevant variables
  select(-c(sex, vviq80, orientation, response, correct_explicit))

# percentage of trials removed in the explicit task
(count(df_explicit) - count(df_explicit_rt)) / count(df_explicit)
# 9091 trials left = 5.9% removed

df_implicit_rt <- 
  df_implicit |>  
  filter(
    correct_implicit == 1 &
    !(subjectid %in% c( 
      "bdispaux", 
      "eleveque", 
      "aleclaire", 
      "dchimenton"))
      ) |>  
  select(-c(sex, vviq80, orientation, response, correct_implicit))

# percentage of trials removed in the implicit task
(count(df_implicit) - count(df_implicit_rt)) / count(df_implicit) 
# 9078 trials left = 6.1% removed
```

```{r}
#| code-summary: "Removing extreme RTs"
#| echo: true
#| output: false

# ═══ First broad RT outlier trials removal ════════════════════════════════════

df_explicit_rt <- 
  df_explicit_rt |>  
  # filtering out extreme RTs
  filter(rt > .25 & rt < 3)

# total percentage of trials removed in the explicit task
(count(df_explicit) - count(df_explicit_rt)) / count(df_explicit)
# 8812 trials left = 8.8% removed

df_implicit_rt <- 
  df_implicit_rt |>  
  filter(rt > .25 & rt < 3)

# total percentage of trials removed in the implicit task
(count(df_implicit) - count(df_implicit_rt)) / count(df_implicit)
# 8963 left = 7.3% removed
```

```{r}
#| label: tbl-rt_means
#| tbl-cap: "Descriptive statistics of the average RTs across the sample in both tasks."

# ═══ RT means table - Both tasks ══════════════════════════════════════════════

df_rt <- 
  list(
  df_explicit_rt |>  rename("Explicit task mean RTs" = rt), 
  df_implicit_rt |>  rename("Implicit task mean RTs" = rt)
  ) |>  
  imap(
    ~select(.x, contains("RT")) |> 
      report() |>  
      as.data.frame() |>  
      select(1:10)
    )

df_rt <- bind_rows(df_rt[[1]], df_rt[[2]])
df_rt

# explicit upper outlier threshold
threshold_explicit <- df_rt$Median[1] + 3*df_rt$MAD[1]
# 1.35

# implicit upper outlier threshold
threshold_implicit <- df_rt$Median[2] + 3*df_rt$MAD[2]
# 1.055

# ─── Listing median rts per subject ───
list(df_explicit_rt, df_implicit_rt) |> 
  imap(
    ~.x |> 
      group_by(subjectid) |> 
      summarise(median_rt = median(rt)) |> 
      arrange(desc(median_rt)) |> 
      ungroup()
    )
```

```{r}

# ═══ Aberrant RT means outliers removal ═══════════════════════════════════════

# ─── Finding outliers ───

df_explicit_rt |> 
  group_by(subjectid) |> 
  summarise(median_rt = median(rt)) |> 
  ungroup() |> 
  filter(median_rt > threshold_explicit) |> 
  arrange(desc(median_rt))
# 3 outliers in the explicit task

df_implicit_rt |>
  group_by(subjectid) |> 
  summarise(median_rt = median(rt)) |> 
  ungroup() |> 
  filter(median_rt > threshold_implicit) |> 
  arrange(desc(median_rt))
# 0 outliers in the implicit task

# ─── Removing specific outliers ───
df_explicit_rt <- 
  df_explicit_rt |> 
  filter(
    !(subjectid %in% c(
      "dchimenton",
      "fc",
      "mbilodeau"
    ))
  )

# total percentage of trials removed in the explicit task
(count(df_explicit) - count(df_explicit_rt)) / count(df_explicit)
# 8688 trials left
# (9664-8688)/9664 # 10.0% out
```


```{r}
# Examination of remaining trials
df_explicit_rt |> 
  group_by(subjectid) |> 
  count() |> 
  arrange(n)
# 3 have very few trials

# ─── Removing specific outliers ───
df_explicit_rt <- 
  df_explicit_rt |> 
  filter(
    !(subjectid %in% c(
      "llhermitte",
      "cmarcenytheault",
      "mbillon"
    ))
  )
# 8569 trials left

df_implicit_rt |> 
  group_by(subjectid) |> 
  count() |> 
  arrange(n)
# implicit trials are ok
```

```{r}
#| code-summary: "Removing outlier trials by-participant"
#| echo: true
#| output: false

# ═══ By-participant MAD outlier detection ═════════════════════════════════════

df_explicit_rt <- # from 8569 trials
  df_explicit_rt |> 
  group_by(subjectid, congruence) |> 
  mutate(
    rt_median = median(rt),
    rt_mad = mad(rt)
    ) |> 
  filter(
    rt < rt_median + 5 * rt_mad
  ) |>
  ungroup()

# total percentage of trials removed in the explicit task
(count(df_explicit) - count(df_explicit_rt)) / count(df_explicit)
# 8408 trials left, 12.9% out


df_implicit_rt <- # from 8963 trials
  df_implicit_rt |> 
  group_by(subjectid, congruence) |> 
  mutate(
    rt_median = median(rt),
    rt_mad = mad(rt)
    ) |> 
  filter(
    rt < rt_median + 5 * rt_mad
  ) |>
  ungroup()

# total percentage of trials removed in the implicit task
(count(df_implicit) - count(df_implicit_rt)) / count(df_implicit)
# 8661 trials left, 10.4% out
```

```{r}
# Examination of remaining trials
df_explicit_rt |> 
  group_by(subjectid) |> 
  count() |> 
  arrange(n)
# explicit trials are ok

df_implicit_rt |> 
  group_by(subjectid) |> 
  count() |> 
  arrange(n)
# implicit trials are ok
```














































