---
title: "Untitled"
---

{{< include 01-setup.qmd >}}

{{< include 02-outlier-procedure.qmd >}}

### Summary RT tables

<!--
#### Whole sample

```{r summary_table}
df_rt <- 
  list( 
  df_implicit_rt |>  rename("Implicit task" = rt),
  df_explicit_rt |>  rename("Explicit task" = rt)
  ) |>  
  imap(
    ~ungroup(.x) |> 
      select(contains("task")) |> 
      report() |>  
      as.data.frame() |>  
      select(1:10)
    )

df_rt <- bind_rows(df_rt[[1]], df_rt[[2]])
df_rt |>  display()
```
--> 

#### Implicit task 

```{r summary_table_im}
df_implicit_rt |> 
  group_by(aphantasia, congruence) |> 
  mutate(
    aphantasia = case_when(
      aphantasia == "yes" ~ "Aphantasic",
      TRUE ~ "Control"
    ),
    congruence = if_else(congruence == "congruent", "Congruent", "Incongruent")
  ) |> 
  rename(
    Group = aphantasia,
    Congruence = congruence
  ) |> 
  summarise(
    "Mean (ms)" = mean(rt),
    "SD (ms)" = sd(rt)
  ) |> 
  display()
```

#### Explicit task 

```{r summary_table_ex}
df_explicit_rt |> 
  group_by(aphantasia, congruence) |> 
  mutate(
    aphantasia = case_when(
      aphantasia == "yes" ~ "Aphantasic",
      TRUE ~ "Control"
    ),
    congruence = if_else(congruence == "congruent", "Congruent", "Incongruent")
  ) |> 
  rename(
    Group = aphantasia,
    Congruence = congruence
  ) |> 
  summarise(
    'Mean (ms)' = mean(rt),
    'SD (ms)' = sd(rt)
  ) |> 
  display()
```

