
# Title proposal

Assessing unconscious visual images in aphantasia: objective measurement using a novel priming paradigm

 > Voici une proposition avec une structure "goal catch -> détail technique" (tout en restant exact), j'ai essayé de mettre en avant les apports clés de l'étude. J'ai pensé à ajouter "proposal for an" avant "objective measurement", ce qui serait plus exact car notre mesure n'est pas encore tout à fait au point, mais c'est moins sexy

 > Overleaf comment: Cette nouvelle version ne commence plus par un paragraphe type "summary"/plan qui dirait en substance "Voici l'imagerie visuelle, voici l'aphantasie, voilà ce qu'on veut faire". Je me suis convaincu d'abandonner ça en lisant des articles récents (par ex. Liu 2023, Monzel 2023, Gulyas 2022): en soi l'abstract fait ce travail de plan, puis les intros commencent directement sur les définitions et le contexte, les études et les problématiques ouvertes, leurs propres questions et objectifs, fin.

# Introduction

    1. Try to imagine: this is mental imagery. Here is how mental imagery is usually defined. It has been studied for quite a while that mental sensory representations are involved in a lot of cognitive processes: here's a list of them with references.

    2. Some have it, some not. This has recently been called aphantasia. It would seem that 3 to 4% of people could have it. There has been quite a few papers on it, correlates, etc. Although self-reports by aphantasics are very consistent across studies, many authors highlight the need to cross the subjective reports with more objective tasks assessing visual imagery. Yet a crucial question on this aspect is still debated: is aphantasia a true absence of mental images, or do people have them but are simply unable to access them consciously? 

Close your eyes and try to mentally visualize your breakfast-table as you sat down to it this morning. Most people would report having a clear image of the scene in their "\textit{mind's eye}": this experience is referred to as visual imagery, commonly defined as the experience of visual sensory information without a direct external stimulus \citep{pearson_human_2019}. Nonetheless, there are great differences between individuals with regard to the vividness of these images, some people even declaring that they have no visual mental images at all. This extreme phenomenon, although already observed in the $19^{th}$ century \citep{galtonSTATISTICSMENTALIMAGERY1880} and noted in various studies since then \citep[e.g.,][among many others]{farahCaseStudyMental1988, fawConflictingIntuitionsMay2009, marksVisualImageryDifferences1973, mckelvieVVIQPsychometricTest1995, paivioImageryAbilityVisual1971, sheehanUnderstandingVariabilityImagery1987, slatterAlphaRhythmsMental1960}, received renewed attention only nine years ago, when \cite{zemanLivesImageryCongenital2015}, in a study that has since become very popular, coined the term "\textit{aphantasia}" to refer to the inability to generate mental images.

Early estimates suggest that aphantasia could concern 3-4\% of the global population \citep[see for instance][]{dancePrevalenceAphantasiaImagery2022, palermo, dawes}. However, many aphantasics may be unaware of their condition, suggesting a potential underestimation of the phenomenon \citep{fawConflictingIntuitionsMay2009, zemanPhantasiaPsychologicalSignificance2020}. Aphantasics differ from the control population on a number of self-report questionnaires of mental imagery and memory \citep{dawesCognitiveProfileMultisensory2020}, such as the Vividness of Visual Imagery Questionnaire \citep[VVIQ;][]{marksVividnessVisualImagery1973}, the Questionnaire upon Mental Imagery (QMI; Sheehan, 1967) \citep[QMI;][]{sheehanShortenedFormBetts1967a}, the Object and Spatial Imagery Questionnaire \citep[OSIQ, but only on the object score;][]{blazhenkovaObjectspatialImageryNew2006}, the Episodic Memory Imagery Questionnaire \citep[EMIQ;][]{dawesCognitiveProfileMultisensory2020} or the Survey of Autobiographical Memory \citep[SAM;][]{palomboSurveyAutobiographicalMemory2013}. Although self-reports by aphantasics are very consistent across studies (reduced autobiographical memory, fewer dreams, intact spatial imagery), many authors stress the need to cross subjective reports with more objective tasks assessing visual imagery. This need is highlighted by the heterogeneity and complexity of aphantasia: for example, some aphantasics report visual mental imagery when dreaming, some have preserved mental imagery in other sensory modalities, while others report a complete absence of conscious mental imagery, both voluntary and involuntary \citep{dawesCognitiveProfileMultisensory2020, zemanPhantasiaPsychologicalSignificance2020}. Yet a crucial question for this assessment is still being debated: is aphantasia a genuine absence of mental images, or do people have them but are simply unable to access them consciously?

    3. Some doubt that mental images could be utterly absent and have suggested that aphantasics might still have unconscious mental images. A very recent study (Liu & Barto 2023) used a behavioural task to assess visual imagery in various domains using imageable words (the French Perception-Imagination Battery) in aphantasics and controls. They found no difference in accuracy, but slower RTs and confidence in the responses, and argued that this result was coherent with the fact that aphantasics had the visual images required to complete the task yet without being conscious of them. Likewise, in a task supposed to use visual imagery to compare the location of a point with an imagined shape, Jacobs 2018 found no difference in accuracy between an aphantasic and control participant, a result that could be interpreted as accrediting the presence of unconscious visual imagery. However, like many studies on aphantasia, due to the conscious nature of the processes at play in these behavioural tasks (with or without sensory imagery), neither study could completely rule out the possibility of alternative strategies (propositional, spatial, etc.) used by aphantasics to solve the tasks.

Some doubt that mental imagery could be utterly absent, and have hypothesized that aphantasics who report having no conscious imagery at all might still have unconscious mental imagery \citep{nanay_unconscious_2020}. As this phenomenon is difficult to identify, very little is known about unconscious, involuntary mental imagery in aphantasia. A recent study (Liu & Barto 2023) used a behavioural task to assess visual imagery in various domains using imageable words (the French Perception-Imagination Battery) in aphantasics and controls. They found no differences in accuracy, but slower RTs and lower confidence in the aphantasics' answers, and argued that this result was consistent with aphantasics having the visual images required to complete the task, albeit without conscious access to them. Similarly, in a task that supposedly required visual imagery to compare the location of a point with an imagined shape, \cite{jacobsVisualWorkingMemory2018} found no difference in accuracy between an aphantasic participant and controls, a result that could be interpreted as accrediting the use of unconscious visual imagery in aphantasia. However, due to the potential conscious processes at play in these behavioural tasks (with or without sensory imagery), neither study could completely rule out the possibility of aphantasics using strategies other than visual imagery (e.g. semantic processing or spatial imagery) to solve the tasks, which prevents from firmly concluding that unconscious mental images exist.
 
    4. In contrast, several studies have demonstrated objective behavioural correlates with the condition: Keogh, Wicken, Kay. Keogh in particular devised a very interesting paradigm to try and answer this question. Let's describe this study's paradigm. In the end, they found no priming in aphantasics, and concluded that they had a real inability to generate mental images, not only lacking metacognition skills.

On the other hand, several studies that sought to develop objective measures assessing visual imagery found differences between aphantasics and controls, such as aphantasics having no skin conductance response to frightening scenarios (Wicken), no automatic pupil dilatation in reaction to imagined brigth stimuli (Kay), or no priming by visual imagery \citep{keoghBlindMindNo2018}, suggesting that aphantasics are truly unable to produce mental images. The latter priming paradigm developed by \cite{keoghBlindMindNo2018} is particularly often cited as a promising and relatively undemanding task for objectively identifying aphantasia, and has already been used for this purpose in several subsequent studies (Keogh, Chang). In their initial study, they investigated visual imagery in aphantasics and controls using a binocular rivalry paradigm: in this task participants were cued either with the letter “R” (for red) or the letter “G” (for green), and had to imagine one of two images, respectively a red-horizontal Gabor or a green-vertical Gabor. After rating the vividness of their mental image, they were presented with both Gabors simultaneously, one in the left eye, the other in the right, and asked to say which color they had seen first. Their results showed that the mental visualization of the Gabors influenced the color seen in the binocular rivalry task for control participants, but not for aphantasics. The authors interpreted this absence of priming in aphantasia as a real inability to generate mental images, and not just a lack of metacognition skills.

    5. Yet, limits of the study (that are also shared by the aforementioned "objective" studies): Participants were explicitly asked to form mental images. As such, they asked people to do things that they probably thought they couldn't do to begin with.

    6. Consequently, these studies cannot rule out the possibility of unconscious mental images in aphantasia. We aim to bridge this gap by designing a paradigm that would allow us to study these unconscious mental images. The objective of this study was to develop a new task inspired by the binocular rivalry used by \cite{keoghBlindMindNo2018}, including a priming task explicitly asking to use mental imagery, and an implicit priming task targeting unconscious mental imagery. Such a task would provide a novel and unprecedented behavioural method to characterize the presence or absence of visual imagery and, by extension, to objectively characterize aphantasia.

While these conclusions are convincing with regard to voluntary imagery (whether in conscious processes or not), they might be inadequate when it comes to involuntary and unconscious mental imagery. A first caveat in this study is that self-diagnosed aphantasics were explicitly asked to voluntarily form mental images and rate their vividness during the task. This may be counter-intuitive, as they were therefore being asked to do something they knew (or believed) they could not do in the first place. It is possible, then, that aphantasics did not fully engage with the task - or did not perform it correctly - because they firmly believed that they would fail to comply with the instructions, due to their awareness of their condition \citep[see][for evidence for demand biases in aphantasia]{cabbaiInvestigatingRelationshipsTrait2023}. Secondly, by using explicit priming, their study did not directly tap unconscious mental imagery, which is typically investigated with implicit priming tasks. Consequently, the binocular rivalry paradigm developed by \cite{keoghBlindMindNo2018} (like other objective measures based on explicit instructions, e.g. Kay, Wicken) cannot exclude the possibility of unconscious mental images in aphantasia.

We aim to fill this gap by designing an implicit priming task that would allow us to study these unconscious mental images. The objective of the present study was to develop a new task inspired by the binocular rivalry used by \cite{keoghBlindMindNo2018}, including a priming task explicitly asking to use mental imagery, along with an implicit priming task targeting unconscious mental imagery. Such a task would provide a novel and unprecedented behavioural method to identify the presence or absence of visual imagery and, by extension, to objectively characterize aphantasia.

In order to create an implicit task, the paradigm was divided into two parts: a prior association phase, and the implicit task itself. The association phase asked the participants to indicate the color of a red horizontal Gabor or a blue vertical Gabor in order to implicitly memorize the color-orientation association. In the subsequent implicit task, a red or blue colored circle was presented as a prime before a target, which was a Gabor either congruent or incongruent with the color seen (see Figures \ref{fig:protocol_asso} and \ref{fig:protocol_implicit} in Section \ref{sec:procedure}). As previous works of our team have shown \citep[e.g.][]{brunelWhenSeeingDog2013, reyMaskWhoWasn2015, reyWhenReactivatedVisual2018}, the prime is assumed to automatically reactivate an unconscious mental image of the associated Gabor. Participants were then asked to indicate the orientation of the target. An explicit task was added for control and comparison where participants were overtly asked to produce a mental image of the Gabors before the targets. In the explicit task, like in Keogh and Pearson’s study, participants were asked to imagine one of the previous Gabors by presenting a letter (R or B) as a cue. A Gabor congruent or incongruent with the color was then presented as a target, and participants were asked to indicate the orientation of the lines of the target.

We expected to show an effect of congruence (i.e.\ a priming effect) in the implicit task by measuring a smaller difference in reaction times of aphantasics between the congruent and the incongruent condition, as opposed to controls who would be faster in the congruent setting (helped by the unconscious mental images of the Gabors). Moreover, to ensure that any priming observed would be the consequence of mental imagery (as opposed to semantic priming, for example), on half of the trials the targets were presented in black and white rather than color. If aphantasia relies only on a difficulty to access mental images, a priming effect should be observed for both groups in the implicit task, but not in the explicit one. If aphantasia relies on a genuine difficulty in creating mental images, no priming effect should be observed for the aphantasia group neither in the implicit nor in the explicit task.

In addition, we carried out a second analysis with a subset of our sample composed solely of aphantasics with a minimal VVIQ score of 16, matched with controls with the highest VVIQ scores. This analysis aimed at answering a frequent interrogation in aphantasia literature about subgroups in aphantasia with differing characteristics: several authors pointed out that the fact of reporting \textit{completely absent} imagery could be qualitatively very distinct from having only \textit{vague} images \citep[e.g.,][]{blomkvistDefiningDiagnosingAphantasia2023, dancePrevalenceAphantasiaImagery2022, murakiInsightsEmbodiedCognition2023} Liu à ajouter. Although based on subjective reports, this difference could be crucial for our paradigm and, as such, called for this additional analysis, as we targeted potentially sensitive unconscious mental images.

# ---

# Current discussion

The objective of the present study was to examine whether aphantasics could form mental images but could not access them consciously, or whether they presented a genuine deficit in the generation of mental images. To this end, we built and tested an implicit priming paradigm on aphantasic and control participants. The analysis revealed striking evidence that only the control group showed a congruence effect in the implicit task, both when examining the full group and only VVIQ extremes. In addition, all groups responded quicker for colored stimuli as opposed to uncolored ones, independently of congruence. Although they responded slightly faster in the congruent condition in the explicit task, the groups did not exhibit a significant congruence effect there. These findings suggest that aphantasia may not simply be a lack of metacognition, as no congruence effect diminishing the RTs in the congruent setting has been observed in the implicit task for aphantasics, but that aphantasia is associated with a genuine deficit in mental image generation. In the aphantasic group, the intensive study of Gabors in a preliminary association task did not allow the presentation of the prime during the implicit task to trigger the emergence of a representation of the studied Gabors in the form of a mental image (conscious or not), which would have facilitated the judgment of the orientation of the lines of congruent Gabors, as demonstrated in the control group.
> Good first paragraph, findings summary

Curiously, besides the gap in visual imagery, the analysis of questionnaire data also yielded a significant difference between aphantasics and controls in reported spatial imagery - assessed by the spatial scale of the OSIQ - in stark contrast with previous studies on aphantasia that used this questionnaire and found no between-group differences \citep{dawesCognitiveProfileMultisensory2020, keoghBlindMindNo2018, bainbridgeQuantifyingAphantasiaDrawing2021}. While this difference is hard to interpret on its own, it is worth noting that although significant, the difference in spatial imagery between the groups is much less pronounced than the difference observed on visual imagery scales, and therefore hard to associate with the same phenomenon of reduction in imagery. Large differences also existed within the aphantasic group hinting that this finding could be specifically tied to our sample and, more generally, that there could exist various sub-types in aphantasia characterized by their variable reliance on different forms of mental representations (e.g. spatial, verbal, kinesthetic).
> Interpretation of spatial difference, good

*The effects of aphantasia have been acknowledged to be difficult to study, as many tasks that ostensibly require visual imagery might also be solved by alternative non-visual strategies, such as the use of internal or covert verbalization \citep{monzelMemoryDeficitsAphantasics2022}. --> NOT HERE* In an interesting study using an implicit priming task where verbal cues (e.g., “banana”) were presented just before pairs of words (e.g., “banana – tomato”) or pictures (e.g., a picture of a banana and of a tomato), aphantasics were slower than non-aphantasics to select pictures that matched prior verbal cues \citep{monzelImagineYouWill2021}. \cite{petilliDatadrivenComputationalModels2021} demonstrated that verbal cues automatically activate the visual properties of referenced objects, affecting the processing of target words even when visual processing is neither requested nor necessary. Furthermore, \cite{amitAsymmetricalRelationshipVerbal2017} provided evidence at the neuronal level that participants generate visual representations, even when the information is meant to be processed verbally. This evidence is consistent with the embodied cognition view of the emergence of representation. Our results therefore coincide with those of \cite{monzelImagineYouWill2021}, and also suggest that the emergence of representations at an implicit/unconscious level is impaired in aphantasia, arguing for a global absence of generation of mental images rather than a sole metacognitive deficit.
> Monzel and implicitly talking about embodied cognition

Nevertheless, our results do not imply that no unconscious representation emerges at all in aphantasia, but they do suggest that the emergence of the sensory features of representations is impaired. As discussed by \cite{keoghBlindMindNo2018}, aphantasics may show abnormal levels of activity in visual areas, frontal areas or both, that alter the creation of mental images and their features. Aphantasia may also be due to disconnections within a putative ventral temporal network, consisting of the fusiform imagery node, the anterior temporal lobes, and the medial temporal lobe, which are another hypothesis proposed for the fundamental network responsible for visual imagery \citep{spagnaChapterVisualMental2022, spagnaVisualMentalImagery2021}.
> Sensory representations might be impaired, little bone to doggy Barto

One could argue that our tasks could be completed using a verbal or propositional strategy based on the color of the stimuli. For instance, in the association phase, participants may have used the propositional strategy of forming the abstract or semantic representation of an association between color and line orientation of the Gabors (e.g., by internally repeating that "blue patches have vertical lines"). During the tasks, when a prime is presented, participants may have used such a representation, which facilitated their response when the color of the target was congruent with the color of the prime. However, our tasks have the decisive advantage of preventing the use of this type of strategy with a condition in which the targets are not colored. As no semantic representation had been previously associated with uncolored targets, the color-based strategy became ineffective. This type of strategy could even have been detrimental, which could explain higher error percentages among control participants in the uncolored condition than in the colored condition. As such, the persistence of the interaction between group and congruence independently of the color condition suggest that our results could not be explained purely by the reliance on propositional strategies. The absence of significant between-group differences in the explicit task might also reflect the use of such strategies. Aphantasics could have used propositional strategies during the 3s imagery phase of the explicit task to "make up" for their absence of visual imagery with another mental association. This other way of apprehending the task could explain their performance equal to that of controls: in contrast, this type of conscious strategy was not available in the implicit task, where aphantasics did not benefit from the congruent condition.
> Discussion of alternative strategies

It should be noted that is often implied in discussions about aphantasia that fast automatic predictive processing and simulation of sensory representations are overall major functional advantages \citep[see for instance][]{monzelMemoryDeficitsAphantasics2022, blomkvistDefiningDiagnosingAphantasia2023}. Nonetheless, couldn't an absence of strong unconscious priming by internal representations be beneficial? Several recent studies suggest that this "buffer" effect of aphantasia on sensory representations could have positive consequences: \cite{wickenCriticalRoleMental2021} showed that aphantasics exhibited dimmed electrophysiological responses to frightening scenarios; \cite{keoghFewerIntrusiveMemories2023} used a laboratory model of PTSD and noted that aphantasics reported fewer intrusive memories when confronted with traumatic films; \cite{konigsmarkGanzflickerExperienceHigh2021} demonstrated, using a rhythmic flicker paradigm to induce pseudo-hallucinations, that aphantasics experienced less anomalous percepts. Another, much less discussed avenue for research on aphantasia, is that of reasoning: we have brought evidence here suggesting that aphantasics simulate less sensory elements in their unconscious representations. Could this constitute an advantage to shorten the gap towards abstraction for cognitive operations? This potentially detrimental effect of visual imagery on reasoning speed is supported by literature on mental models and reasoning \citep[e.g.,][]{knauffSpatialReasoningNo2001,knauffVisualImageryCan2002, knauffSpaceReasonSpatial2013,johnson-lairdChapterOneUnified2013}.
Studies at the interface of the fields of mental imagery, embodied cognition and reasoning could provide new answers to these questions, which could in turn shed light on the amazing range of functional properties of the various types of mental representations.
> Positive note at the end on potential positive outcomes of aphantasia

In sum, our findings provided evidence suggesting that aphantasia does not result from lacking metacognition, but from a true absence of unconscious and involuntary mental imagery. The consistency of the congruence effect obtained in our implicit task shows that this priming paradigm is a promising and reliable basis for future behavioral tasks aiming to characterize mental imagery objectively and implicitly, without relying on participant introspection.  
> Conclusion

## Structure of the current discussion

---

# Ideas - Only one paragraph to modify

## Embodied cognition from the current intro then related Monzel

<!-- Additional insights of unconscious and involuntary mental imagery come from embodied cognition which suggests that sensorimotor simulation might be a kind of unconscious and involuntary mental imagery  \citep{murakiInsightsEmbodiedCognition2023}. A sensorimotor simulation is the re-creation of the states in which the individual's perceptual and motor systems were in a previous experience, as well as the individual's emotional and introspective states in that experience \citep[e.g.,][]{barsalouGroundedCognition2008, barsalouSimulationSituatedConceptualization2009, dijkstraMechanismsEmbodiment2015, milleSensMemoire2021, versaceContentsLongtermMemory2009, versaceActInIntegratedView2014, versaceCognitionIncarneeCognition2018}. From this re-creation emerges a representation that can reach consciousness in the form of a mental image of, for instance, an apple, if the neurons in the perceptual and motor systems that were activated during our confrontations with apples are reactivated in the present situation. However, it is assumed that these emerging representations do not systematically reach consciousness voluntarily. For instance, 

although reading the word “apple” triggers the emergence of multimodal representations (e.g., of its appearance, taste, smell, sound and grip) without necessarily reaching consciousness, it has been shown in various cross-modal priming studies that these representations can still influence subsequent behavioural responses \citep[e.g.][]{brunelSensoryNatureKnowledge2010, reyMaskWhoWasn2015, reyAutomaticVisualSimulation2017, valletPerceptualNatureCrossModal2010}. As such, these multimodal sensory representations coudl constitute a form of unconscious, involuntary mental images capable of influencing conscious behaviour. -->


*New Monzel:* 
<!-- In an interesting study using an implicit priming task where verbal cues (e.g., “banana”) were presented just before pairs of words (e.g., “banana – tomato”) or pictures (e.g., a picture of a banana and of a tomato), aphantasics were slower than non-aphantasics to select pictures that matched prior verbal cues \citep{monzelImagineYouWill2021}. \cite{petilliDatadrivenComputationalModels2021} demonstrated that verbal cues automatically activate the visual properties of referenced objects, affecting the processing of target words even when visual processing is neither requested nor necessary. Furthermore, \cite{amitAsymmetricalRelationshipVerbal2017} provided evidence at the neuronal level that participants generate visual representations, even when the information is meant to be processed verbally. This evidence is consistent with the embodied cognition view of the emergence of representation. Our results therefore coincide with those of \cite{monzelImagineYouWill2021}, and also suggest that the emergence of representations at an implicit/unconscious level is impaired in aphantasia, arguing for a global absence of generation of mental images rather than a sole metacognitive deficit. -->

<!-- The effects of aphantasia have been acknowledged to be difficult to study, as many tasks that ostensibly require visual imagery might also be solved by alternative non-visual strategies, such as the use of internal or covert verbalization \citep{monzelMemoryDeficitsAphantasics2022}. 
*A recurrent challenge when studying aphantasia is that many tasks that are often considered to require visual imagery could also be solved by other non-visual strategies, such as the use of internal or covert verbalization \citep{monzelMemoryDeficitsAphantasics2022}. In that vein, it could be argued that our tasks could be completed using a verbal or propositional strategy based on the color of the stimuli.*-->

## Is it really imagery? My paragraph on embodied

*Counter-argument to address in the discussion: did we really assess "imagery", or "mental images" in our study?*
As we did not instruct participant to produce any specific mental content in the implicit task, we could question whether our study really assessed "mental imagery" as it is commonly defined. This question has to do with the very concept of "unconscious mental images". Should we consider that they exist, those images could neither be produced voluntarily by the participant nor experienced consciously, and are therefore by definition very hard to objectify. To shed some light on this question, the mental construct we refer to here as "unconscious mental images" could be compared to the concept of "sensorimotor simulation" developed in the field of embodied cognition, which has been assumed to be a kind of unconscious mental imagery  \citep{murakiInsightsEmbodiedCognition2023}. A sensorimotor simulation is the re-creation of the states in which the individual's perceptual and motor systems were in a previous experience, as well as the individual's emotional and introspective states in that experience \citep[e.g.,][]{barsalouGroundedCognition2008, barsalouSimulationSituatedConceptualization2009, dijkstraMechanismsEmbodiment2015, milleSensMemoire2021, versaceContentsLongtermMemory2009, versaceActInIntegratedView2014, versaceCognitionIncarneeCognition2018}. From this re-creation emerges a representation that can reach consciousness in the form of a mental image of, for instance, an apple, if the neurons in the perceptual and motor systems that were activated during our confrontations with apples are reactivated in the present situation. However, it is assumed that these emerging representations do not systematically reach consciousness voluntarily. Although reading the word “apple” triggers the emergence of multimodal representations (e.g., of its appearance, taste, smell, sound and grip) without necessarily reaching consciousness, it has been shown in various cross-modal priming studies that these representations can still influence subsequent behavioural responses \citep[e.g.][]{brunelSensoryNatureKnowledge2010, reyMaskWhoWasn2015, reyAutomaticVisualSimulation2017, valletPerceptualNatureCrossModal2010}. As such, these multimodal sensory representations coudl constitute a form of unconscious, involuntary mental images capable of influencing conscious behaviour. In light of this concept, saying that aphantasics might not have unconscious mental images could then be rephrased as saying that aphantasics do not "simulate" the visual (and potentially sensory in general) properties of concepts or incoming information. 

\cite{monzelImagineYouWill2021} has provided early evidence on aphantasia that could be interpreted within this framework. In study using an implicit priming task where verbal cues (e.g., “banana”) were presented before pairs of words (e.g., “banana – tomato”) or pictures (e.g., a picture of a banana and of a tomato), aphantasics were found to be slower than non-aphantasics in selecting pictures that matched prior verbal cues. In this specific situation, \cite{petilliDatadrivenComputationalModels2021} demonstrated that verbal cues automatically activate visual properties of referenced objects and affect subsequent processing of target words, even when visual processing is neither requested nor required. Furthermore, \cite{amitAsymmetricalRelationshipVerbal2017} provided evidence at the neuronal level that participants generate visual representations in such tasks, even when the information is meant to be processed verbally. This evidence is consistent with the embodied cognition view of the emergence of multimodal representations. Accordingly, our results are consistent with those of \cite{monzelImagineYouWill2021} and further suggest that the emergence of sensory representations at an unconscious level is impaired in aphantasia, arguing for a global absence of mental image generation rather than a single metacognitive deficit.
 
# Last intro shit

<!-- Aphantasics differ from the control population on a number of self-report questionnaires of mental imagery and memory \citep{dawesCognitiveProfileMultisensory2020}, such as the Vividness of Visual Imagery Questionnaire \citep[VVIQ;][]{marksVividnessVisualImagery1973}, the Questionnaire upon Mental Imagery (QMI; Sheehan, 1967) \citep[QMI;][]{sheehanShortenedFormBetts1967a}, the Object and Spatial Imagery Questionnaire \citep[OSIQ, but only on the object score;][]{blazhenkovaObjectspatialImageryNew2006}, 

the Episodic Memory Imagery Questionnaire \citep[EMIQ;][]{dawesCognitiveProfileMultisensory2020} or the Survey of Autobiographical Memory \citep[SAM;][]{palomboSurveyAutobiographicalMemory2013}. Although self-reports by aphantasics are very consistent across studies (reduced autobiographical memory, fewer dreams, intact spatial imagery), many authors stress the need to cross subjective reports with more objective tasks assessing visual imagery. -->

Aphantasics often report reduced or absent sensory imagery in various modalities, fewer and less rich dreams \citep{dawesCognitiveProfileMultisensory2020}, reduced episodic and autobiographical memory \citep{dawesCognitiveProfileMultisensory2020}, yet with intact spatial imagery \citep{dawesCognitiveProfileMultisensory2020}.
---


# Trash


<!-- # Current introduction -->

<!-- *Let's sum up each paragraph* -->

<!-- Most human beings can form clear images in the "\textit{mind's eye}", such as when recalling a past episode: this phenomenon is referred to as "mental imagery". Nonetheless, there is a large variability between individuals in the vividness of these images, whether they be voluntary or involuntary. A minority of people is unable to prevent intrusive images in their minds, as seen in Post-Traumatic Stress Disorder (PTSD). At the opposite end of the spectrum, another minority of people is unable to even conjure a mental image, a condition recently coined "\textit{aphantasia}" \citep{zemanLivesImageryCongenital2015}. Aphantasia represents an interesting knock-out model for studying mental imagery. However, much remains unknown about this condition, and most of the studies on aphantasia rely on subjective reports, leaving the question of whether mental images can exist without reaching consciousness unresolved. It has been showed that mental images can reach consciousness voluntarily or involuntarily and influence perception as a prime \citep{kwokMeasuringThoughtControlFailure2019}. Going even further, it was argued this priming effect of mental images could also occur involuntarily without them reaching consciousness. Using a priming paradigm, the aim of the present study was to objectively assess the conscious and unconscious mental imagery in aphantasia. -->

<!-- A classical definition of visual imagery is ‘seeing’ in the absence of the appropriate immediate sensory input \citep{kosslynCaseMentalImagery2006}. More recently, visual imagery has been defined as representations and the accompanying experience of sensory information without a direct external stimulus \citep{pearson_human_2019}. It was even proposed that mental imagery is a perceptual processing in the early sensory cortices, V1, V2, V4/V8, and MT, that is not triggered directly by sensory input \citep{nanay_multimodal_2018, nanay_unconscious_2020, nanay_mental_2023}. Numerous studies have provided evidence for an involvement of sensory mental representations in cognition. For instance, visual imagery would be solicited in autobiographical memory and future thinking \citep[e.g.][]{purkartAmeliorerRememorationEvenements2019, schacterCognitiveNeuroscienceConstructive2007, schacterRememberingImagineFuture2007}, working memory \citep[e.g.][]{reyWhenReactivatedVisual2018, serencesStimulusSpecificDelayActivity2009}, language comprehension \citep[e.g.][]{dilsVisualMotionAftereffect2010}, moral reasoning \citep[e.g.][]{amitYouSeeEnds2012}, dreams \citep[e.g.][]{horikawaNeuralDecodingVisual2013} or expectations about upcoming tasks \citep[e.g.][]{kokPriorExpectationsEvoke2014}.  -->

<!-- The nature of mental images has been debated for decades. On the one hand, it was argued that visual imagery relies on language-like symbolic and descriptive representations \citep[referred to as the "propositional" position;][]{pylyshynImageryDebateAnalogue1981}. On the other hand, it was argued that visual imagery relies on representations that include the sensorimotor features of the components of the item being represented and the spatial relationships between those components \citep[referred to as the "depitcive" position;][]{kosslynMediumMessageMental1981}. Today, the imagery debate seems to have settled with the advent of neuroimagery, given the substantial evidence indicating that visual imagery involves depictive representations \citep{pearson_mental_2015}. However, some clarifications remain to be made as to the nature of mental images, including whether they are conscious or unconscious, voluntary or involuntary. -->

<!-- Mental imagery is mainly viewed and studied as the ability to voluntarily form mental images, and to experience them consciously (explicit mental imagery). This ability gives the possibility to consciously inspect and manipulate mental images to perform cognitive tasks, and those mental images are viewed as analogous to perceived images. For instance, objects in visual mental images can be rotated, and the farther they are rotated, the more time is required, as it would be for perceived images \citep{shepardMentalRotationThreeDimensional1971}. In the same manner, objects in visual mental images can be scanned, and the farther one scans, the more time is required \citep{kosslynInformationRepresentationVisual1975}. The analogy can also be observed in priming paradigms, where conscious and voluntary mental images prime perception in the same way as perceived images (although the priming is typically weaker). For instance, mental imagery priming has been evidenced using binocular rivalry tasks. In binocular rivalry tasks, different images, such as red and green Gabors with different line orientation, are presented to the two eyes, and participants’ visual experience alternates between these two images. At the same time, participants are asked to report which color is dominant. It was show that when asking participants to form the mental image of a red apple just before reporting the dominant Gabor’s color, the mental image acted as a prime and the red Gabor won out systematically in the subsequent binocular rivalry task \citep[e.g.,][]{kwokMeasuringThoughtControlFailure2019, pearsonEvaluatingMindEye2011}. -->

<!-- However, mental images can also be triggered by internal associations or external events and involuntarily reach consciousness \citep{pearsonPhantomPerceptionVoluntary2015}. For instance, it was shown that mental images involuntarily reached consciousness when involuntary autobiographical memories were triggered or primed by irrelevant cue phrases in a vigilance task (\citealp{schlagmanInvoluntaryAutobiographicalMemories2008}; see also \citealp{barzykowskiPrimingInvoluntaryAutobiographical2018}; \citealp{blackwellInducingPositiveInvoluntary2020}). Interestingly, it has been proposed that mental imagery could also be both involuntary and unconscious \citep{nanay_unconscious_2020}. The existence of such a form of mental imagery has been questioned \citep{pearson_human_2019}, but striking evidence comes from perceptual processing studies. For instance, several studies have shown using masking paradigms that a stimulus can still be perceived yet without a conscious experience of it \citep[e.g.][]{goodaleSightUnseenExploration2013, kentridgeAttentionAwarenessBlindsight1999, kouiderLevelsProcessingNonconscious2007, weiskrantzBlindsightCaseStudy2009}. It was also evidenced that stimuli presented to the contralesional side of unilateral neglect patients’ visual field can prime their responses, suggesting a unconscious perception of the stimulus \citep[e.g.][]{bertiVisualProcessingAwareness1992, ladavasImplicitAssociativePriming1993}. Consistently with the proposed view of mental imagery, evidence suggests that unilateral neglect patients can also show similar a behaviour for the contralesional side of their visual images – a phenomenon called "imaginal neglect" \citep{coslettNeglectVisionVisual1997, guarigliaUnilateralNeglectRestricted1993}. These findings suggest that mental imagery could also be unconscious.  -->

<!-- Additional insights of unconscious and involuntary mental imagery come from embodied cognition which suggests that sensorimotor simulation might be a kind of unconscious and involuntary mental imagery  \citep{murakiInsightsEmbodiedCognition2023}. A sensorimotor simulation is the re-creation of the states in which the individual's perceptual and motor systems were in a previous experience, as well as the individual's emotional and introspective states in that experience \citep[e.g.,][]{barsalouGroundedCognition2008, barsalouSimulationSituatedConceptualization2009, dijkstraMechanismsEmbodiment2015, milleSensMemoire2021, versaceContentsLongtermMemory2009, versaceActInIntegratedView2014, versaceCognitionIncarneeCognition2018}. From this re-creation emerges a representation that can reach consciousness in the form of a mental image of, for instance, an apple, if the neurons in the perceptual and motor systems that were activated during our confrontations with apples are reactivated in the present situation. However, it is assumed that emerging representations do not systematically reach consciousness voluntarily. For instance, reading the word “apple” will automatically trigger the emergence of multimodal representations (e.g., of its look, taste, smell, sound and grip) without necessarily reaching consciousness, but that can act as a prime and influence a subsequent behavioral response, as it was shown in cross-modal priming studies \citep[e.g.][]{brunelSensoryNatureKnowledge2010, reyMaskWhoWasn2015, reyAutomaticVisualSimulation2017, valletPerceptualNatureCrossModal2010}. As such, these multimodal representations might be a form of unconscious and involuntary mental images. -->

<!-- Thus, mental imagery could equally be voluntarily or involuntarily conscious, as well as involuntarily unconscious. To further investigate mental imagery, a useful approach is to focus on a type of population that exhibits an apparent absence of mental imagery. Although the high variability in visual imagery and its correlates have long been studied \citep[e.g.,][among many others]{farahCaseStudyMental1988, fawConflictingIntuitionsMay2009, galtonSTATISTICSMENTALIMAGERY1880, marksVisualImageryDifferences1973, mckelvieVVIQPsychometricTest1995, paivioImageryAbilityVisual1971, sheehanUnderstandingVariabilityImagery1987, slatterAlphaRhythmsMental1960}, this phenomenon received renewed attention ten years ago when \cite{zemanLossImageryPhenomenology2010} reported the case of a patient, MX, who rated himself as experiencing almost no visual imagery on standard questionnaires, yet performed normally on standard tests of perception and visual memory. After a popular description of the case in the media, over twenty individuals recognized themselves in the case of the patient MX and contacted the authors. Yet unlike patient MX, they had been experiencing this lack of visual imagery since they were born: \cite{zemanLivesImageryCongenital2015} studied their condition, and named it "\textit{aphantasia}". Aphantasia now refers to individuals reporting reduced or completely absent visual imagery, representing approximately 3 to 4\% of the global population according to first estimations \citep[see for instance][]{dancePrevalenceAphantasiaImagery2022}. However, many aphantasics may be unaware of their condition, suggesting a potential underestimation of the phenomenon \citep{fawConflictingIntuitionsMay2009, zemanPhantasiaPsychologicalSignificance2020}. As shown by \cite{dawesCognitiveProfileMultisensory2020}, aphantasics differ from the control population on a number of self-report questionnaires of mental imagery and memory, including the Vividness of Visual Imagery Questionnaire \citep[VVIQ;][]{marksVividnessVisualImagery1973}, the Questionnaire upon Mental Imagery (QMI; Sheehan, 1967) \citep[QMI;][]{sheehanShortenedFormBetts1967a}, the Object and Spatial Imagery Questionnaire \citep[OSIQ, but only on the object score;][]{blazhenkovaObjectspatialImageryNew2006}, the Episodic Memory Imagery Questionnaire \citep[EMIQ;][]{dawesCognitiveProfileMultisensory2020} and the Survey of Autobiographical Memory \citep[SAM;][]{palomboSurveyAutobiographicalMemory2013}. Since self-reported and subjective questionnaires were used, it only suggests a deficit in conscious, mainly voluntary, mental imagery. -->

<!-- However, aphantasia is a complex and heterogeneous condition. For instance, some aphantasics report vivid mental imagery when dreaming, suggesting that a form of conscious mental imagery is spared for them \citep{dawesCognitiveProfileMultisensory2020, zemanPhantasiaPsychologicalSignificance2020}. Some aphantasics report a complete absence of conscious mental imagery, both voluntary and involuntary. But very little is known about unconscious and involuntary mental imagery in aphantasia. It was hypothesized that the behavior of aphantasics that report having no imagery at all could be balanced by an unscathed unconscious mental imagery \citep{nanay_unconscious_2020}. \cite{jacobsVisualWorkingMemory2018} did a case study of an aphantasic named AI where they supplemented questionnaires with more objective measures of mental imagery. In this study, participants were presented with the name of a geometric shape (e.g., triangle), and were required to form a mental image of the shape and project it within a space delimited by a square frame. Immediately afterward, a visual mask was briefly presented, followed by a point drawn somewhere within the space delimited by a square frame. Participants then had to determine whether the point would be inside the previously imagined shape. Surprisingly, AI exhibited the same performance as control participants. An interpretation of this result could be that AI's response was based on an involuntary and unconscious mental image triggered by the presented shape name as a cue, whereas this mental image could potentially reach consciousness or even be voluntarily generated for control participants. -->

<!-- Another study by \cite{keoghBlindMindNo2018} using an objective measure for mental imagery can be taken as an example to support the claim that at least some aphantasics have unconscious mental images. In this study, 15 participants with aphantasia and 209 control participants were cued either with the letter “R” (for red) or the letter “G” (for green), to imagine for 6 sec one of two images (a red-horizontal Gabor or a green-vertical Gabor). After that, they were required to rate the vividness of their mental image on a Likert-type scale from 1 to 4, then performed a binocular rivalry task immediately afterwards. They were presented  simultaneously with both Gabors for 750 ms, one in the left visual hemifield, the other in the right, and had to report which color they saw first. Their results showed that while the prior mental imagery of Gabor primed the color seen in the binocular rivalry task for control participants, participants with aphantasia showed no priming. The authors interpreted the absence of priming as a lack of sensory and phenomenal imagery in aphantasia rather than a lack of metacognition. In this regard, the findings suggest that individuals with aphantasia lack both conscious and unconscious imagery. Yet this interpretation might be rediscussed. -->

<!-- First caveat in this study aphantasics were self-diagnosed and were explicitly asked to voluntarily form mental images and rate their vividness during the task. This may seem counter-intuitive, given that they are being asked to do something they know they cannot do (or do not believe they are able to). It is then possible that aphantasics were not completely engaged in the task because they had a strong belief that they would fail to comply with the instructions, especially since they are self-diagnosed aphantasics and are aware of their condition \citep[see][for evidence for demand biases in aphantasia]{cabbaiInvestigatingRelationshipsTrait2023}.  Second, the study did not involve a task requiring unconscious mental imagery, it thus difficult to conclude if aphantasics have a selective deficit for conscious mental imagery, but intact unconscious mental imagery, or whether both forms of imagery are deficient. By using explicit priming, their paradigm did not involve unconscious mental imagery, which is theoretically triggered by implicit priming tasks. As such, we believe that comparing the results of an explicit priming task those of an implicit priming task would be an interesting approach to test if aphantasics have a complete deficit in mental imagery, including unconscious mental imagery, or if the deficit is restricted to conscious mental imagery. -->

<!-- # Structure of the current introduction -->

   <!-- > Here are mental images. Some have them, even sometimes intrusive, others have not. These latter could be used to study unconscious imagery. The issue is knowing whether mental images can be unconscious. So here our study wants to study them on aphantasia -->
   
  <!-- > Here's a definition of mental imagery. Based on neuroimagery, a lot of people think that it relies on sensory stuff. Here's also where it's very useful. -->
  
  <!-- > There was a debate on sensory or propositional. Now neuroimagery has gone by, and ok it's sensory. But the voluntary/involuntary and conscious/unconscious images is debated. -->
  
  <!-- > Mental imagery is mostly studied as conscious and voluntary. Now here are examples that show that mental images have sensory properties. *This is incohenrent, no real point here* -->
  
  <!-- > Mental images can be involuntary and conscious. It can be argued that they could also be unconscious: perceptual processing can be unconscious (phantom perception, simulation). Somehow there could be unconscious mental images in the wrong side of hemineglect patients? -->
  
  <!-- > Sensorimotor simulation, a concept from embodied cognition, can also be interpreted as a form of unconscious mental imagery, and can be argue to exist based on cross-modal priming studies -->
  
  <!-- > So here we have it, conscious or unconscious, voluntary or involuntary mental imagery. Aphantasia could be useful to study mental imagery. Here is the timeline of aphantasia. *No* -->

  <!-- > Evidence is lacking to argue on the existence of unconscious mental imagery in aphantasia. Here is the study of Jacobs. Can be an argument, ain't it? -->
  
  <!-- > Keogh can also be interpreted as arguing for the existence of unconscious mental imagery. Here is their study. But their conclusion is... Not that? *Incohent organization* -->
  
  <!-- > The problem with Keogh is that they asked people to do things that they probably thought they couldn't do to begin with. As it was conscious mental imagery, it's hard to conclude on the proper absence of unconscious imagery, isn't it? -->

# Theoretically acceptable version of the current introduction

1. *The approach of the intro is wrong: we do not want to study mental images thanksto aphantasia, but to study the inconscious mental iomages in aphantasia. So here's the acceptable approach:* Here's aphantasia: some have suggested that aphantasics could have unconscious mental images. We want to examine this possibility by designing a paradigm that would allow us to study these unconscious mental images.

2. Definitions of mental imagery*? Why not. Especially to present Nanay's idea that they could have unconscious mental images. The historical part is useless. Therefore:*, going straight into the hypotheses that it could be unconscious and involuntary.

3. Argument about the possibility of unconscious mental images: mental images are perceptual processing without the external stimulus, and perceptual processing can be unconscious, so maybe mental images can be unconscious. *The parallel with the concept of sensorimotor simuylation from embopdiued cognition would go into the discussion. Muraki too.* 

4. Evidence is lacking to argue for or against the existence of unconscious mental imagery in aphantasics. Jacobs can be interpreted, why not. *Here we could add Jianghao and Barto?*

5. Keogh has the most interesting study on evaluating the objective presence or absence of mental images in aphantasics: here is the description of their study. The problem is that they asked people to do things that they probably thought they couldn't do to begin with. As it was conscious mental imagery, it's hard to conclude on the proper absence of unconscious imagery.

<!-- # Old introduction -->

<!-- *Let's sum up each paragraph* -->

<!-- Close your eyes and try to mentally visualize your breakfast-table as you sat down to it this morning. While most people would report having an image that is as bright as the actual scene, some will report having no image in mind. This phenomenon has recently been called aphantasia. Research dedicated to this condition is constantly expanding, but many questions remain regarding the cognitive functioning of aphantasics. Crucially, it remains unclear whether these people still have mental images but cannot access them, or if it is a genuine inability to generate them. The present study aims to provide new insights to this very topical question. -->
 
<!-- More than 2 millennia ago, philosophers referred to seeing with the mind's eye (mentis oculi) as the ability to form sensory mental representations of what has been seen through the eyes (e.g., Cicero, 1840). Nowadays, this ability is referred to as visual imagery. Numerous studies have provided evidence for an involvement of sensory mental representations in cognition. For instance, visual imagery would be solicited in autobiographical memory and future thinking (e.g., Purkart et al., 2019; Schacter et al., 2007; Schacter & Addis, 2007), working memory (e.g., Rey et al., 2018; Serences et al., 2009), language comprehension (e.g., Dils & Boroditsky, 2010), moral reasoning (e.g., Amit & Greene, 2012), dreams (e.g., Horikawa et al., 2013) or expectations about upcoming tasks (e.g., Kok et al., 2014).  -->

<!-- However, the format of these mental representations remained unclear for decades. A debate on visual imagery and the nature of mental representations started in the 1960s. On the one hand, it was argued that the physical features of an object are stored in a form that preserves the physical relationship of the elements that constitute it – that is, as a depictive and pictorial representation (referred to as the "pictorial" or "analogical" position; Kosslyn, 1981). This position relied on empirical evidence showing, for instance, that objects in visual mental images can be rotated (the further they are rotated, the more time is required, Shepard & Metzler, 1971), and scanned (the further one scans, the more time is required; Kosslyn, 1975). On the other hand, it was argued that visual imagery relies on language-like symbolic and descriptive representations (referred to as the "propositional" position; Pylyshyn, 1981). Empirical evidence showed that the systematic relations between reaction time and image properties (reflecting the time taken by participants to scan to the location of a given item) can disapear when appropriate instructions are given that are designed to encourage participants to interpret the task as solving a problem by using a certain representational format (Pylyshyn, 1981). -->

	<!-- The debate took a new shape in the early 1990s with the advent of neuroimagery. It has been shown that visual mental imagery, like visual perception, involves activity in the V1 area of the visual cortex (Albers et al., 2013; Kosslyn et al., 2006; Slotnick et al., 2005; Stokes et al., 2009). Also, using algorithms trained during perception, it was shown that mental image could be "decoded" from activity patterns in the V1 area of the visual cortex (Harrison & Tong, 2009; Naselaris et al., 2015; Serences et al., 2009). Because area V1 is depictive by nature, it was proposed that these findings alone suggest that visual mental images involve depictive representations. At this point, one may think that the debate would finally be over.  -->
	
	<!-- However, in 2003 an interesting study examined the possibility that, during the early years of this debate, researchers’ views were shaped by their own conscious experiences with visual imagery. A survey of 150 psychologists, philosophers, and neuroscientists working in the field showed that those who experienced their own visual imagery as vivid and picture-like recalled being more sympathetic in 1980 to the view that mental images are picture-like (Reisberg et al., 2003). Similarly, those who experienced vivid mental images and who regularly used their mental images in cognition were more inclined to believe that the topic deserves more research. It would seem, therefore, that individual differences in terms of imagery may guide our intuitions about the existence or not of mental images. This inter-individual difference in visual imagery had already been anticipated in the 19th century by Galton (1880) who, using his breakfast table survey, reported cases of people not experiencing mental images. Much more recently, Zeman et al. (2010) reported the case of a patient, MX, who rated himself as experiencing almost no visual imagery on standard questionnaires, yet performed normally on standard tests of perception, visual imagery and visual memory. After a popular description of the case in the media, over twenty individuals recognized themselves in the case of the patient MX and contacted the authors. Unlike to patient MX they had been experienced this lack of visual imagery since they were born. At this point, Zeman started to explore the features of their condition, and named it aphantasia (Zeman et al., 2015). -->
 
	<!-- Aphantasia refers now to people who report reduced visual imagery. Il would represent between 3 and 4% of the world population, but aphantasics are often unaware of their condition it might be then underestimated (Faw, 2009; Zeman et al., 2020). As shown by Dawes et al. (2020), aphantasics differ from the control population on a number of self-report questionnaires of mental imagery and memory, including the Vividness of Visual Imagery Questionnaire (VVIQ; Marks, 1973), the Questionnaire upon Mental Imagery (QMI; Sheehan, 1967), the Object and Spatial Imagery Questionnaire (OSIQ, but only on the object score; Blajenkova et al., 2006), the Episodic Memory Imagery Questionnaire (EMIQ) and the Survey of Autobiographical Memory (SAM). However, since self-reported and subjective questionnaires were used, it remains unclear whether people with aphantasia have images in their mind without being able to access them) or have a genuine inability to generate mental images. This question was partly addressed in a recent study using an elegant objective measure of mental imagery (Keogh & Pearson, 2018). -->
	
	<!-- In this study (Keogh & Pearson, 2018), 15 participants with aphantasia and 209 control participants were cued either with the letter “R” (for red) or the letter “G” (for green), to imagine for 6 sec one of two images (a red-horizontal Gabor or a green-vertical Gabor). After that, they were required to rate the vividness of their mental image on a Likert-type scale from 1 to 4. Immediately after they performed a binocular rivalry task. They were presented with simultaneously each of the two Gabor for 750 ms, one in the left visual hemifield, the other in the right, and participants had to report which color they saw first. Their results showed that while the prior mental imagery of gabor primed the color seen in the binocular rivalry task for control participants, participants with aphantasia showed no priming. The authors interpreted the absence of priming as a genuine inability to generate mental images in aphantasia rather than a poor metacognition. -->
	
<!-- However, in the study of Keogh and Pearson (2018) participants with aphantasia were explicitly asked to voluntarily form mental images and rate their vividness. This may seem counterintuitive, given that they are being asked to do something they know they cannot do. It is possible that aphantasics can have non-conscious mental images but cannot voluntarily create them. In other words, they can maybe form mental images automatically but not explicitly. Keogh and Pearson (2018) may have failed to observe a priming effect because they asked explicitly aphantasics to generate mental images. We think that an implicit priming would be an interesting way to test the genuine inability to generate mental images. -->

<!-- The present study -->
	<!-- We modified the paradigm used by Keogh & Pearson (2018) in order to turn it into an implicit priming task. An explicit priming task was kept as a control condition. As it is usually done, participants were allocated to the aphantasia group or the control group according to their VVIQ score. In order to create an implicit task, two different phases were presented. First, red-horizontal Gabor and blue-vertical Gabor were each presented 50 times and participants were asked to indicate the color of each Gabor to implicitly memorize the color-orientation association. Second, in the test phase, a red or blue colored circle was presented as a prime before a target which was either a congruent or incongruent Gabor. As many previous works of our team have shown (e.g., Brunel et al., 2013; Rey et al., 2015, 2018), the prime is assumed to automatically reactivate a mental image of the associated Gabor. Participants were then asked to indicate the orientation of the target. We expect to measure a priming or congruence effect by showing a smaller difference in term of reaction times at the orientation task in the congruent condition compared to the incongruent one. In the explicit task, like in Keogh and Pearson’s study, participants were cued to imagine one of the previous Gabors for 3 sec by presenting a letter (R or B) as a cue. Right after the 3 sec of mental imagery, a congruent or incongruent Gabor was presented as a target and participants were asked to indicate the orientation of the lines of the target. In addition, in order to be sure that when a priming is measured it was made through mental images (and not based on a semantic priming), in half of the trials the targets were presented in black and white rather than in color. If aphantasia relies only on a difficulty to access mental images, a priming effect should be observed for both groups in the implicit task, but not in the explicit one. If aphantasia relies on a genuine difficulty in creating mental images, no priming effect should be observed for the aphantasia group neither in the implicit nor in the explicit task. -->
  <!-- > Explanation of our study, badly done -->

<!-- ## Structure of the old introduction -->

<!--  > Try to imageine: this is mental imagery. Some have it, some not. This has recently been called aphantasia. There has been quite a few papers on it, but a crucial question about the condition is still debated: is it a genuine inability to generate mental images, or do people have them but are simply unable to access them consciously? -->

<!--  > Our study aims at bringing new arguments to answer this question. *Ok* -->

<!--  > It has been studied for quite a while that mental sensory representations are involved in a lot of cognitive processes: here's a list of them with references. *Why not, debatable* -->

<!--  > Yet the very format of these representations has also been debated for a long time: some argue that they were very sensory-like in nature, others argued that the sensory aspect was only epiphenomenal - all with experimental findings. *Useless* -->

<!--  > Yet the very format of these representations has also been debated for a long time: some argue that they were very sensory-like in nature, others argued that the sensory aspect was only epiphenomenal - all with experimental findings. *Useless* -->

<!-- 	> With the advent of neuroimagery, it did seem that this was over, as a lot of activations in the sensory regions have been observed. *Useless* -->

<!--  > This research might be biased by the very subjective experience of reasearchers. These interindividual difference might therefore be more important than anticipated for theoretical conclusions. Oh, by the way, here's a recent history of how aphantasia was coined. *Useless* -->

<!-- 	> Now there's aphantasia. It would seem that 3 to 4% of people could have it. Their reports on psychometric questionnaires are very coherent in their framing of the condition. Now the fateful question: do they really not have mental images, or are they only unable to reach them consciously? *Why not* -->

<!-- 	> Keogh & Pearson devised a very interesting paradigm to try and answer this question. *Ok* -->

<!-- 	> Let's describe this study's paradigm. In the end, they found no priming in aphantasics, and concluded that they had a real inability to generate mental images, not only lacking metacognition skills. *Ok* -->

<!--   > Limits of the study: -->
<!--   > Participants were explicitly asked to form mental images: that should be highlighted drastically, how can one answer to an instruction if they are convinced beforehand that they are unable to follow it? *Ok* -->

<!--   > Explanation of our study, badly done *Ok* -->

# Theoretically acceptable version of the old introduction

1. Try to imageine: this is mental imagery. Some have it, some not. This has recently been called aphantasia. There has been quite a few papers on it, but a crucial question about the condition is still debated: is it a genuine inability to generate mental images, or do people have them but are simply unable to access them consciously? Our study aims at bringing new arguments to answer this question. *Ok*

2. It has been studied for quite a while that mental sensory representations are involved in a lot of cognitive processes: here's a list of them with references. *Why not, debatable*

3. Now there's aphantasia. It would seem that 3 to 4% of people could have it. Their reports on psychometric questionnaires are very coherent in their framing of the condition. Now the fateful question: do they really not have mental images, or are they only unable to reach them consciously? *Why not*

4. Keogh & Pearson devised a very interesting paradigm to try and answer this question. *Ok*

5. Let's describe this study's paradigm. In the end, they found no priming in aphantasics, and concluded that they had a real inability to generate mental images, not only lacking metacognition skills. *Ok*

6. Limits of the study:

7. Participants were explicitly asked to form mental images: that should be highlighted drastically, how can one answer to an instruction if they are convinced beforehand that they are unable to follow it? *Ok*

8. Explanation of our study, badly done *Ok*

# ----

## Synthesis of the reusable ideas

1. Try to imagine: this is mental imagery. Here is how mental imagery is usually defined. It has been studied for quite a while that mental sensory representations are involved in a lot of cognitive processes: here's a list of them with references.

2. Some have it, some not. This has recently been called aphantasia. It would seem that 3 to 4% of people could have it. There has been quite a few papers on it, correlates, etc. Although self-reports by aphantasics are very consistent across studies, many authors highlight the need to cross the subjective reports with more objective tasks assessing visual imagery. Yet a crucial question on this aspect is still debated: is aphantasia a true absence of mental images, or do people have them but are simply unable to access them consciously? 

3. Some doubt that mental images could be utterly absent and have suggested that aphantasics might still have unconscious mental images. A very recent study (Liu & Barto 2023) used a behavioural task to assess visual imagery in various domains using imageable words (the French Perception-Imagination Battery) in aphantasics and controls. They found no difference in accuracy, but slower RTs and confidence in the responses, and argued that this result was coherent with the fact that aphantasics had the visual images required to complete the task yet without being conscious of them. Likewise, in a task supposed to use visual imagery to compare the location of a point with an imagined shape, Jacobs 2018 found no difference in accuracy between an aphantasic and control participant, a result that could be interpreted as accrediting the presence of unconscious visual imagery. However, like many studies on aphantasia, due to the conscious nature of the processes at play in these behavioural tasks (with or without sensory imagery), neither study could completely rule out the possibility of alternative strategies (propositional, spatial, etc.) used by aphantasics to solve the tasks.

4. In contrast, several studies have demonstrated objective behavioural correlates with the condition: Keogh, Wicken, Kay. Keogh in particular devised a very interesting paradigm to try and answer this question. Let's describe this study's paradigm. In the end, they found no priming in aphantasics, and concluded that they had a real inability to generate mental images, not only lacking metacognition skills.

5. Yet, limits of the study (that are also shared by the aforementioned "objective" studies): Participants were explicitly asked to form mental images. As such, they asked people to do things that they probably thought they couldn't do to begin with.

6. Consequently, these studies cannot rule out the possibility of unconscious mental images in aphantasia. We aim to bridge this gap by designing a paradigm that would allow us to study these unconscious mental images. The objective of this study was to develop a new task inspired by the binocular rivalry used by \cite{keoghBlindMindNo2018}, including a priming task explicitly asking to use mental imagery, and an implicit priming task targeting unconscious mental imagery. Such a task would provide a novel and unprecedented behavioural method to characterize the presence or absence of visual imagery and, by extension, to objectively characterize aphantasia.










