
# ═══ Project-wide settings for rendering ══════════════════════════════════════

# table of contents
toc: true
toc-depth: 3
toc-expand: 2
number-sections: true
number-depth: 2
fig-align: center
fig-cap-location: bottom
tbl-cap-location: top

# setting for proper numbering of sections
crossref: 
  chapters: true
  
# code reading options
warning: false
error: false
message: false

# format-specific options
format: 
  html:
    echo: true
    code-fold: true
    cap-location: bottom
  docx: 
    echo: false