
# ═══ Project-wide settings for rendering ══════════════════════════════════════

# table of contents
toc: true
toc-depth: 3
toc-expand: 3
number-sections: true
number-depth: 2
fig-align: center
fig-asp: 0.618
fig-format: svg
fig-cap-location: bottom
tbl-cap-location: margin

# setting for proper numbering of sections
crossref: 
  chapters: true
  
# code reading options
warning: false
error: false
message: false

# format-specific options
format: 
  html:
    echo: true
    code-fold: true
    cap-location: bottom
  docx: 
    echo: false