
# Results

## Explicit task results

The best model for the RTs in the explicit task included a random intercept by participant and a slope by participant on the color condition (AIC = 19,478, cAIC = 19,478, null model AIC = 19,582), and had a substantial explanaory power (conditional $R^{2}$ = .52). The parameters of the best model for the explicit task are displayed in \ref{table1}. 

*table caption*
The model's intercept corresponds to the aphantasic group, in the congruent and colored condition. The parameter for each factor thus represents the difference between the other factor levels (controls, incongruent, and uncolored) and this intercept.
*end of table caaption*

The significant parameters in this task are the Color and the interaction between the Group and the Congruence conditions. The main effect of Color indicates that participants responded quicker in the colored condition ($\beta$  = .11,  95% CI [0.06, 0.17], t(8891) = 3.89, p < .001, marginal contrast (colored - uncolored) = -.14, CI = [-.17 ; -.1], SE = .02, p < .001), although this effect has no interaction with the other variables. The interaction between Group and Congruence (\beta = .09, 95% CI [0, .17], t(8891) = 2.14, p = .033) reveals that non-aphantasics responded slower in the uncongruent condition, as this contrast is the only significant one in this interaction (marginal contrast (non-aphantasic congruent - incongruent) = -.11, CI = [-.17; -.05], SE = .02, p < .001). These effects are illustrated in \ref{fig4}. Both estimates are $< 0.2$, which denotes a small effect size according to most standardized differences interpretation guidelines (e.g. Cohen, 1988; Gignac & Szodorai, 2016; Lovakov & Agadullina, 2021).

\begin{tabular}{l}
\hline
x\\
\hline
Table: Fixed Effects\\
\hline
\\
\hline
|Parameter                                                         | Coefficient |   SE |           95\% CI | t(8891) |      p |\\
\hline
|:-----------------------------------------------------------------|:-----------:|:----:|:----------------:|:-------:|:------:|\\
\hline
|(Intercept)                                                       |       -0.10 | 0.08 |    (-0.27, 0.07) |   -1.19 | 0.235  |\\
\hline
|aphantasia (no)                                                   |        0.01 | 0.13 |    (-0.24, 0.27) |    0.10 | 0.921  |\\
\hline
|congruence (uncongruent)                                          |        0.03 | 0.03 |    (-0.03, 0.08) |    0.98 | 0.327  |\\
\hline
|color (uncoloured)                                                |        0.11 | 0.03 |     (0.06, 0.17) |    3.89 | < .001 |\\
\hline
|aphantasia (no) × congruence (uncongruent)                        |        0.09 | 0.04 | (7.39e-03, 0.17) |    2.14 | 0.033  |\\
\hline
|aphantasia (no) × color (uncoloured)                              |        0.05 | 0.04 |    (-0.04, 0.14) |    1.11 | 0.268  |\\
\hline
|congruence (uncongruent) × color (uncoloured)                     |    9.66e-03 | 0.04 |    (-0.07, 0.09) |    0.25 | 0.804  |\\
\hline
|(aphantasia (no) × congruence (uncongruent)) × color (uncoloured) |       -0.02 | 0.06 |    (-0.14, 0.09) |   -0.41 | 0.680  |\\
\hline
\end{tabular}

## Implicit task results

The best model for the RTs in the implicit task included a random intercept by participant and a slope by participant on the congruence condition (AIC = 22,107, cAIC = 22,107, null model AIC = 22,116), and had a substantial explanaory power (conditional $R^{2}$ = .35). 

The parameters of the best model for the implicit task are displayed in \ref{table3}. 

The significant parameters in this task are the Group and the interaction between the Group and the Congruence conditions. The main effect of Group ($\beta$  = -.22,  95% CI [-.42, -.01], t(8877) = -2.08, p = .038) indicates that aphantasics responded overall slower across conditions (marginal contrast (controls - aphantasics) = -.22, CI = [-.17 ; -.1], SE = .02, p < .001). The interaction between Group and Congruence (\beta = .09, 95% CI [0, .17], t(8891) = 2.14, p = .033) also reveals that non-aphantasics responded slower in the incongruent condition, as this contrast is once again the only significant one in this interaction (marginal contrast (non-aphantasic congruent - incongruent) = -.11, CI = [-.17; -.05], SE = .02, p < .001). 

The only significant parameter is the interaction between Group and Congruence. This interaction shows that non-aphantasics only responded slower in the incongruent condition, which is the only significant contrast (Marginal contrast (non-aphantasic congruent - incongruent) = `r c_im_gcn[1,3]`, CI = $[`r c_im_gcn[1,4]`;`r c_im_gcn[1,5]`]$, SE = `r c_im_gcn[1,6]`, $p = `r c_im_gcn[1,9]`$). This effect is represented in @fig-model_implicit_ggarrange. This estimate $\lt 0.2$, which denotes a *very small* effect size.
